### ISSUE TITLE
Tag name with single quote in it

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/xblock-in-video-quiz#219]
Hi. The current latest tag 1.6.1 has a trailing single quote in it.

![image](https://github.com/user-attachments/assets/56059b50-dbaf-49b4-9134-fc721c870264)

Maybe remove, create, and push again?

**Comment by CodeWithEmad** [comment]
@farhan Sorry to ping you, but looks like you've been working on this and you might be able to fix this

**Comment by farhan** [comment]
Sure, we will work on it

**Comment by farhan** [comment]
@CodeWithEmad Thanks for flagging it.
It's fixed: https://github.com/openedx/xblock-in-video-quiz/releases
Please close the ticket, thanks!
